### ISSUE TITLE
Crashing without error

### ISSUE THREAD

**Issue by Skipperio** [crmarsh/discord-linux-bugs#27] opened 2016-05-02 16:18 UTC
After about 3 mins it crashes without error. I can see when it crash just window that pop up and disappear.

**Comment by Jibodeah** [comment] 2016-05-02 21:09
Possible dupe of #21? Try running Discord in gdb and then take a look at what gdb says when it crashes/freezes.

**Comment by crmarsh** [comment] 2016-05-03 15:45
I think this is fixed in 0.0.6, lmk

**Closed** 2016-05-03 16:10 UTC
Labels: bug, fix-pending
