### ISSUE TITLE
Debugging Speech chat freezes and it closes on Kubuntu 16.04

### ISSUE THREAD

**Issue by Serkan-devel** [crmarsh/discord-linux-bugs#47] opened 2016-05-28 12:33 UTC
When I click the Debugging option at speech chat it opens a new window, freezes then closes discordapp by itself.

**Comment by Leseratte10** [comment] 2016-05-30 04:52
Happens for me too, on Ubuntu 15.10 with Discord. Any debug logs we could give you to fix this?

**Comment by Leseratte10** [comment] 2016-05-30 04:55
(Seems to be a duplicate of #12 )

**Comment by Serkan-devel** [comment] 2016-06-01 14:35
where do I find the logs?

**Comment by crmarsh** [comment] 2016-06-01 15:40
Yeah, this is the same as #12. I have a guess about what the bug is, I'll try to get a fix for it soon.

**Closed by crmarsh** 2016-06-01 15:40 UTC
Labels: duplicate
