### ISSUE TITLE
Tray icon missing

### ISSUE THREAD

**Issue by ultimate255** [crmarsh/discord-linux-bugs#65] opened 2016-07-22 23:35 UTC
Discord tray icon missing on the Wingpanel

Elementary OS 0.3.2 Freya
Pantheon Desktop

**Comment by GreyAsteroid** [comment] 2016-07-23 08:31
Duplicate of https://github.com/crmarsh/discord-linux-bugs/issues/4

It's a problem with electron that can be tracked here https://github.com/electron/electron/issues/5050

Can be worked around by launching with the environment set to Unity
`env XDG_CURRENT_DESKTOP=Unity /usr/share/discord-canary/DiscordCanary`

**Closed** 2016-08-03 18:19 UTC
Labels: duplicate
