### ISSUE TITLE
Decryption error, dropping packet when joining voice chat

### ISSUE THREAD

**Issue by feanor12** [crmarsh/discord-linux-bugs#229] opened 2017-09-06 10:00 UTC
When I join a voice channel in the discord-canary build it connects slowly and when connected I see "Decryption error, dropping packet" in the console output. After a few seconds the connection status of the channel shows:
RTC-Server : eu-west483
average Ping of 4545ms 
last Ping is 2853ms.

Happens in 0.0.2 discord and 0.0.24 discord-canary.
The Firefox app works.

I'm using Arch Linux
Name                     : openssl
Version                  : 1.1.0.f-2

Name                     : opus
Version                  : 1.2.1-1

Name                     : pulseaudio
Version                  : 10.0-3

Name                     : linux
Version                  : 4.12.8-2

Name                     : gtk2
Version                  : 2.24.31-1

Name                     : gconf
Version                  : 3.2.6-5

Name                     : libnotify
Version                  : 0.7.7-1

Name                     : libxss
Version                  : 1.2.2-2

Name                     : glibc
Version                  : 2.25-7

Name                     : alsa-lib
Version                  : 1.1.4.1-1

Name                     : nspr
Version                  : 4.16-1

Name                     : nss
Version                  : 3.32-1

Name                     : libc++
Version                  : 4.0.1-1

I added an attachment of a [strace](https://github.com/crmarsh/discord-linux-bugs/files/1280640/discord-canary.strace.zip) log. I started the app an it was connecting to a voice channel. after connected I said something and the decryption error appeared. After that I therminated with Crtl+C. The stdout was:
#strace -o discord-canary.strace discord-canary
DiscordCanary 0.0.24
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/michael/.config/discordcanary/0.0.24/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
20090: Decryption error, dropping packet.
^C%

**Comment by 2E0PGS** [comment] 2017-09-09 18:36
same issue here, 
Ubuntu Unity 16.04
openssl/xenial-updates,now 1.0.2g-1ubuntu4.8 amd64

I also did a stace to check which files it uses for caches etc. cleaned the install of any trance of discord I could find... reinstalled 2.0.0 still cannot connect to voice without dropped packets and ping of over 2000. 

However I do not see same issues on Ubuntu 17.04 MATE with:
openssl/zesty-updates,now 1.0.2g-1ubuntu11.2 amd64

**Comment by 2E0PGS** [comment] 2017-09-09 18:39
I am guessing its a openssl or some sort of stored/cached key issue. I will try a fresh install of 16.04 ubuntu mate on a VM updated in a bit and see if that has issues.

**Comment by 2E0PGS** [comment] 2017-09-11 01:40
Ok so I noticed it doesn't happen on a fresh Ubuntu or Mate install either 16.04.3 or 17.04. However both have newer kernels than the effected machine. I wonder what kernel your running @feanor12 ?

**Comment by feanor12** [comment] 2017-09-11 07:58
I' running on 4.12.10-1. I will try to see if it happens on a fresh install as well.

**Comment by feanor12** [comment] 2017-09-11 08:03
On a fresh arch install, it works as well. Seems to be some sort of caching issue

**Comment by 2E0PGS** [comment] 2017-09-11 12:18
I tried a fresh install of Ubuntu and even down graded its kernel to same as effected machine. Worked on fresh install even after down grade. This defiantly seems like some cached key or file is causing this issue or maybe another system package. My laptops discord updated ok but that is running less packages and runs newer Ubuntu kernel / branch.

If Discord could point me to all effected directories that it stores files in I can ensure I clear all traces of it and then try reinstalling but I have already tried this a few times and even used strace to ensure I didn't miss any locations of storage.

Also all deps would be nice to know.

**Comment by feanor12** [comment] 2017-10-04 17:36
When I start discord-canary I get 

```
Okt 04 19:33:08 michael-arch dbus[427]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service'
Okt 04 19:33:08 michael-arch dbus[427]: [system] Activation via systemd failed for unit 'dbus-org.bluez.service': Unit dbus-org.bluez.service not found.
```

in "`journalctl -xf`"

The bluetooth service is not called bluez anymore, I think. Maybe that can be a reason ...

**Comment by feanor12** [comment] 2017-10-04 17:38
I tried running discord via an [AppImage](https://github.com/simoniz0r/AppImages/releases/tag/discord-stable) and the error still persists.

**Comment by feanor12** [comment] 2017-10-06 16:59
Using a different/new user changes nothing -> system thing

**Comment by feanor12** [comment] 2017-11-17 13:30
Today I did an update "pacman -Syu" and I can not reproduce this in discord canary anymore. In discord stable it still exists.

**Comment by crmarsh** [comment] 2017-11-17 17:50
I think this is fixed in canary and ptb now.

**Closed by crmarsh** 2017-11-17 17:50 UTC

**Comment by 2E0PGS** [comment] 2017-11-17 18:59
![image](https://user-images.githubusercontent.com/15659301/32963908-64039b42-cbc9-11e7-818e-a5f2a399e388.png)
Sure is! What was the cause!?
Thanks for finally fixing this!

**Comment by 2E0PGS** [comment] 2017-11-17 19:03
nope the audio cuts in and out on receive. also the icon in tray blinks... fixed one issue created another it seems.

**Comment by feanor12** [comment] 2017-11-17 19:08
The ping looks good. People told me that they can hear me well, but I was 5 seconds late.

**Comment by crmarsh** [comment] 2017-11-17 19:45
I didn't work on it directly, from what I understand there was a race condition that was clobbering a receive buffer some of the time.

**Comment by 2E0PGS** [comment] 2017-12-10 01:22
Still getting problems with delayed audio on both stable and PBT. Only working option is web browser version for on Linux. That sometimes has users report my audio is delayed. Eitherway this is still an issue... RTC connection is slow, ping goes down to normal 20 ms ish but receive and send audio is delayed and intermittent...
