### ISSUE TITLE
error message after updating

### ISSUE THREAD

**Issue by imyota** [crmarsh/discord-linux-bugs#122] opened 2016-11-05 09:09 UTC
![screenshot from 2016-11-05 05-04-54](https://cloud.githubusercontent.com/assets/23275361/20028962/fbe74cde-a315-11e6-82ec-8400d24c4b33.png)

After updating this error message popped up when tried to open discord.

**Comment by ahjolinna** [comment] 2016-11-05 11:45
I notice this also happening for my friend, it seems that discord(-updater?) had been running in the background all the time, after he had (force) closed it everything worked just fine again.

**Comment by sidneycrestani** [comment] 2016-11-05 11:48
@ahjolinna you're right. Just do a `sudo killall DiscordCanary` and launch again

**Comment by imyota** [comment] 2016-11-05 17:30
it worked after your magic @sidneycrestani ty!!

**Comment by crmarsh** [comment] 2016-11-09 17:26
Gonna mark this as a dupe of #128 because I already renamed that one to what the problem is.

**Closed by crmarsh** 2016-11-09 17:26 UTC
Labels: duplicate
